name: Build and release
on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install wget
        run: choco install wget --no-progress

      - name: Install deps
        working-directory: ./src
        run: |
          pip install -r requirements.txt 
          pip install pyinstaller pypiwin32

      # - name: Bundle application
      #   run: pyinstaller main.spec
      #   #  --noconfirm --onedir --windowed --add-data "C:\Users\name\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter;customtkinter/" --add-data --hidden-import plyer.platforms.win.filechooser --hidden-import plyer.platforms.linux.filechooser

      # - name: PyInstaller Windows
      #   uses: JackMcKew/pyinstaller-action-windows@main
      #   with:
      #     path: src
      - name: Download ffmpeg binary
        run: |
          mkdir src/ffmpeg
          wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -O ffmpeg.zip
          unzip ffmpeg.zip
          mv ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe src/ffmpeg/

      - name: Create version file
        run: |
          echo ${{ github.ref_name }} > src/version

      - name: Bundle application
        working-directory: ./src
        run: python -m eel main.py web -n ytdlp-gui --onefile --noconsole --hidden-import plyer.platforms.win.filechooser --hidden-import plyer.platforms.linux.filechooser --add-data ./ffmpeg:ffmpeg --add-data version

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: src/dist/ytdlp-gui.exe

  github-release:
    permissions:
      contents: write
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/**/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
