on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - if: matrix.platforms.os == 'ubuntu-latest'
        name: Install mtdev
        run: sudo apt install libmtdev-dev

      - name: Install deps
        run: pip install -r requirements.txt pyinstaller

      - name: Bundle application
        run: pyinstaller main.py --hidden-import plyer.platforms.win.filechooser --hidden-import plyer.platforms.linux.filechooser

      - if: matrix.platforms.os == 'windows-latest'
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/main.exe

      - if: matrix.platforms.os == 'ubuntu-latest'
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/main.exe

  github-release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/**/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
