on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install deps
        working-directory: ./src
        run: pip install -r requirements.txt pyinstaller

      # - name: Bundle application
      #   run: pyinstaller main.spec
      #   #  --noconfirm --onedir --windowed --add-data "C:\Users\name\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter;customtkinter/" --add-data --hidden-import plyer.platforms.win.filechooser --hidden-import plyer.platforms.linux.filechooser

      # - name: PyInstaller Windows
      #   uses: JackMcKew/pyinstaller-action-windows@main
      #   with:
      #     path: src

      - name: Bundle application
        working-directory: ./src
        run: python3 -m eel main.py web -n ytdlp-gui --onefile --noconsole --hidden-import plyer.platforms.win.filechooser --hidden-import plyer.platforms.linux.filechooser

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: src/dist/ytdlp-gui.exe

  github-release:
    permissions:
      contents: write
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/**/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
