on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "tag_name=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"
      - name: Generate tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.date.outputs.tag_name }}',
              sha: context.sha
            })
